apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-flask-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-flask-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

