apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  namespace: development
spec:
  selector:
    app: python-flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Explicitly set NodePort
  type: NodePort
