apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-deployment
  namespace: stage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask
        image: ajin0809/python-flask-app:latest  # Use a stage-specific image if needed
        ports:
        - containerPort: 80
